theme: jekyll-theme-slate
title: Shreyansh Jain
description: Welcome to my Portfolio
name: Shreyansh Jain | Portflio
avatar: https://github.com/bafnasb/bafnasb.github.io/0.jpeg
footer-links:
  email: bafnashanky1996@gmail.com
  facebook : bafna.shreyanshjain
  github : bafnasb
  instagram :_shreyanshbafna_
  linkedin : jshreyansh
  twitter : bafna_sb
